version: '3'

services:
  # banco de dados para API GO
  mysql:
    image: mysql:latest
    container_name: db-produtos-go
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports: 
      - 3305:3306
    volumes:
      - ./go-api/docker/mysql:/var/lib/mysql 
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  # banco de dados para API Nest.js
  db:
    image: mysql:latest
    container_name: db-pagamento-mysql
    restart: always
    environment:
      MYSQL_DATABASE: pagamento_nest
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3304:3306
    volumes:
      - ./microsservico-pedidos/docker/mysql:/var/lib/mysql 
  
  # levantar container do rabbitmq 
  rabbtimq:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin 
      - RABBITMQ_DEFAULT_PASS=admin